"""Run the analysis. Two backends, one prompt.

`agent`  — the analyst is the Claude session you are already running this in.
           The dossier is written to a request file; the agent reads it, does
           the analysis and writes the JSON back. No API key, no extra spend
           beyond the subscription already paying for the session.

`api`    — the analyst is the Claude API, for running this unattended.
           Same system prompt, same task, same schema.

Both go through `verify` afterwards, so neither is trusted on its word.
"""

from __future__ import annotations

import json
import os
import re
from pathlib import Path

import requests

from .harvest import Dossier
from .prompts import SYSTEM, build_prompt
from .verify import VerificationReport, verify

DEFAULT_MODEL = "claude-opus-5"
API_URL = "https://api.anthropic.com/v1/messages"


class AnalysisPending(Exception):
    """Raised by the agent backend when the analysis has not been written yet."""


def request_path(workdir: Path, slug: str) -> Path:
    return workdir / f"{slug}.request.md"


def analysis_path(workdir: Path, slug: str) -> Path:
    return workdir / f"{slug}.analysis.json"


def write_request(dossier: Dossier, workdir: str | Path, slug: str) -> Path:
    """Write the exact prompt the analyst should answer."""
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    path = request_path(workdir, slug)
    path.write_text(
        "<!-- Analysis request generated by promise_audit. The analyst reads this\n"
        f"     file and writes its JSON answer to {slug}.analysis.json -->\n\n"
        "# SYSTEM\n\n" + SYSTEM + "\n\n# TASK\n\n" + build_prompt(dossier.as_briefing())
    )
    return path


def extract_json(text: str) -> dict:
    """Pull the JSON object out of a model response that may be fenced."""
    text = text.strip()
    fence = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.S)
    if fence:
        text = fence.group(1)
    else:
        start, end = text.find("{"), text.rfind("}")
        if start != -1 and end > start:
            text = text[start:end + 1]
    return json.loads(text)


def analyse_via_api(dossier: Dossier, model: str = DEFAULT_MODEL,
                    max_tokens: int = 8000, timeout: int = 300) -> dict:
    """Send the dossier to the Claude API. Requires ANTHROPIC_API_KEY."""
    key = os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        raise RuntimeError(
            "ANTHROPIC_API_KEY is not set. Use --backend agent to have the Claude "
            "session you are already in do the analysis instead.")
    resp = requests.post(
        API_URL,
        headers={"x-api-key": key, "anthropic-version": "2023-06-01",
                 "content-type": "application/json"},
        json={"model": model, "max_tokens": max_tokens, "system": SYSTEM,
              "messages": [{"role": "user", "content": build_prompt(dossier.as_briefing())}]},
        timeout=timeout,
    )
    resp.raise_for_status()
    body = resp.json()
    text = "".join(block.get("text", "") for block in body.get("content", []))
    return extract_json(text)


def analyse_via_agent(dossier: Dossier, workdir: str | Path, slug: str) -> dict:
    """Read the analysis the in-session agent wrote for this dossier."""
    workdir = Path(workdir)
    path = analysis_path(workdir, slug)
    if not path.exists():
        req = write_request(dossier, workdir, slug)
        raise AnalysisPending(
            f"No analysis found at {path}.\n"
            f"The request has been written to {req}.\n"
            f"Ask the Claude session to read that file and write its JSON answer to {path}, "
            f"then run this command again.")
    raw = path.read_text()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return extract_json(raw)


def analyse(dossier: Dossier, backend: str = "agent", workdir: str | Path = ".",
            slug: str = "company", model: str = DEFAULT_MODEL,
            ) -> tuple[dict, VerificationReport]:
    if backend == "api":
        analysis = analyse_via_api(dossier, model=model)
    elif backend == "agent":
        analysis = analyse_via_agent(dossier, workdir, slug)
    else:
        raise ValueError(f"unknown backend {backend!r}; use 'agent' or 'api'")
    analysis.setdefault("company", dossier.company)
    analysis["backend"] = backend
    if backend == "api":
        analysis["model"] = model
    return verify(analysis, dossier)
